Repository GSM-GOGO/GSM-GOGO-Server, pull requests merged in 2024-05, with the labels that each got.

#167 :fire: 동일한 기능이 실행되는 스케줄이 중복됨
  gsmgogo-batch/src/main/java/team/gsmgogo/job/AlertJob.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/DailyJob.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/ResetCountJob.java
  gsmgogo-batch/src/main/java/team/gsmgogo/scheduler/AlertScheduler.java
  gsmgogo-batch/src/main/java/team/gsmgogo/scheduler/DailyScheduler.java
  gsmgogo-batch/src/main/java/team/gsmgogo/scheduler/ResetScheduler.java
Labels: 2️⃣Priority: Low, ♻️Refactor

#174 동전 던지기 횟수 조회 기능 추가
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/controller/GameController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/controller/dto/response/CoinCountResponse.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/service/CoinTossCountService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/service/impl/CoinTossCountServiceImpl.java
Labels: ✨Feature, 0️⃣Priority: High

#173 경기 조회 API 필드 추가
  gsmgogo-api/src/main/java/team/gsmgogo/domain/match/controller/dto/response/MatchInfoDto.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/match/service/impl/MatchServiceImpl.java
Labels: ✨Feature, 0️⃣Priority: High

#172 마이페이지 배팅한 경기 조회
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/controller/UserController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/dto/response/BetMatchInfoDto.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/dto/response/BetMatchResponse.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/dto/response/BetMatchResultDto.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/QueryUserBetMatchService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/impl/QueryUserBetMatchServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/common/CalculatePointRequest.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/match/repository/MatchQueryDslRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/matchresult/repository/MatchResultQueryDslRepository.java
Labels: ✨Feature, 0️⃣Priority: High

#175 Hotfix/calculate
  gsmgogo-api/src/main/java/team/gsmgogo/global/common/CalculatePoint.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/CalculateMatchResultJob.java
Labels: 0️⃣Priority: High, ⚙ Setting

#177 버튼게임 기능 추가
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/controller/GameController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/controller/dto/request/ButtonGameRequest.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/service/ButtonGameService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/service/impl/ButtonGameServiceImpl.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/CalculateButtonGameJob.java
  gsmgogo-batch/src/main/java/team/gsmgogo/scheduler/ButtonGameCalculateScheduler.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/buttongame/entity/ButtonGameEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/buttongame/enums/ButtonType.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/buttongame/repository/ButtonGameRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/buttongameparticipate/entity/ButtonGameParticipate.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/buttongameparticipate/repository/ButtonGameParticipateQueryDslRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/buttongameparticipate/repository/ButtonGameParticipateRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/buttongameparticipate/repository/dto/ButtonGameResultDto.java
Labels: ✨Feature, 0️⃣Priority: High

#178 버튼게임 상태 조회 API
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/controller/GameController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/controller/dto/response/ButtonGameResponse.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/service/ButtonGameStateService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/service/impl/ButtonGameStateServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/buttongameparticipate/repository/ButtonGameParticipateRepository.java
Labels: ✨Feature, 0️⃣Priority: High

#180 버튼게임 조회 기능 추가
  .idea/misc.xml
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/controller/GameController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/controller/dto/request/ButtonGameRequest.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/controller/dto/response/ButtonGameResponse.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/service/ButtonGameStateService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/service/impl/ButtonGameStateServiceImpl.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/CalculateButtonGameJob.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/buttongame/entity/ButtonGameEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/buttongame/repository/ButtonGameQueryDslRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/buttongameparticipate/entity/ButtonGameParticipate.java
Labels: ✨Feature, 0️⃣Priority: High

#179 버튼게임 수정사항
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/service/impl/ButtonGameServiceImpl.java
  gsmgogo-batch/src/main/java/team/gsmgogo/scheduler/ButtonGameCalculateScheduler.java
Labels: ✨Feature, 0️⃣Priority: High
