Repository GSM-GOGO/GSM-GOGO-Server, pull requests merged in 2024-04, with the labels that each got.

#128 이어달리기 성별 Validation 수정
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamNormalSaveServiceImpl.java
Labels: 0️⃣Priority: High, ⚙ Setting

#131 CORS OPTIONS 메서드 요청 캐시 시간 설정
  gsmgogo-api/src/main/java/team/gsmgogo/global/config/SecurityConfig.java
Labels: 1️⃣Priority: Medium, 🐛Bug, ♻️Refactor

#134 포매이션 조회시 발생하는 불필요한 쿼리 개선 N+1
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamFormationGetServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/team/repository/TeamQueryDslRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/team/repository/TeamRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/team/repository/TeamRepositoryImpl.java
Labels: 1️⃣Priority: Medium, ♻️Refactor

#136 유저가 2학년이거나 3학년이면 2~3학년 유저 리스트를 표시함
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/controller/UserController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/QueryUserListService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/impl/QueryUserListServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/repository/UserJpaRepository.java
Labels: 🐛Bug, 0️⃣Priority: High

#139 축구 인원수를 8명으로 변경
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamSaveServiceImpl.java
Labels: 🐛Bug, 0️⃣Priority: High

#140 일반 경기 종목에 8자 줄넘기 추가
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamNormalSaveServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/normalteamparticipate/enums/NormalTeamType.java
Labels: 🐛Bug, 0️⃣Priority: High

#127 로그아웃 API
  .gitignore
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/controller/AuthController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/LogoutService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/LogoutServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/config/SecurityConfig.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/security/jwt/filter/TokenFilter.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/auth/entity/BlackListRedisEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/auth/repository/BlackListJpaRepository.java
Labels: ✨Feature, 0️⃣Priority: High

#144 User Info API 배드민턴 조건 추가
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/controller/UserController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/QueryUserInfoService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/QueryUserListService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/impl/QueryUserInfoServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/impl/QueryUserListServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/repository/UserJpaRepository.java
Labels: 🐛Bug, 0️⃣Priority: High

#146 더 이상 사용하지 않는 API deprecated
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/TeamController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/controller/UserController.java
Labels: 0️⃣Priority: High, ⚙ Setting

#147 Oauth Base URL 변경
  gsmgogo-api/src/main/java/team/gsmgogo/global/feign/GauthInfo.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/feign/GauthToken.java
Labels: 🐛Bug, 0️⃣Priority: High

#149 팀 배팅 API
  gsmgogo-api/src/main/java/team/gsmgogo/domain/bet/controller/BetController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/bet/controller/dto/BetRequest.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/bet/service/BetService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/bet/service/impl/BetServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/bet/repository/BetJpaRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/entity/UserEntity.java
Labels: 1️⃣Priority: Medium, ✨Feature

#154 경기 조회시 승리, 패배 팀의 포인트를 계산하는 로직 수정
  gsmgogo-api/src/main/java/team/gsmgogo/global/common/CalculatePoint.java
Labels: 🐛Bug, 0️⃣Priority: High

#153 배팅 결과 정산 Batch 로직 작성
  .github/workflows/gogo_cd.yml
  gsmgogo-api/build.gradle
  gsmgogo-api/src/main/java/team/gsmgogo/global/config/SecurityConfig.java
  gsmgogo-batch/build.gradle
  gsmgogo-batch/src/main/java/team/gsmgogo/job/CalculateMatchResultJob.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/ResetLoginCountJob.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/controller/BatchController.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/controller/dto/CalculateMatchResultRequest.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/validator/CalculateMatchValidator.java
  gsmgogo-batch/src/main/resources/application.yml
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/bet/repository/BetJpaRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/match/entity/MatchEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/match/repository/MatchJpaRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/matchresult/repository/MatchResultJpaRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/entity/UserEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/enums/Role.java
Labels: ✨Feature, 0️⃣Priority: High

#156 데일리 룰렛 기능 추가
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/controller/GameController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/controller/dto/response/DailyRouletteResponse.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/service/DailyRouletteRollService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/game/service/impl/DailyRouletteRollServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/game/entity/GameEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/game/repository/GameJpaRepository.java
Labels: ✨Feature, 0️⃣Priority: High

#161 경기 조회 API 배드민턴 인원 필드 추가
  gsmgogo-api/src/main/java/team/gsmgogo/domain/match/controller/dto/response/MatchInfoDto.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/match/controller/dto/response/MatchResultDto.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/match/service/impl/MatchServiceImpl.java
Labels: 🐛Bug, 0️⃣Priority: High

#159 배팅 가능 시간 설정
  gsmgogo-api/src/main/java/team/gsmgogo/domain/bet/service/impl/BetServiceImpl.java
Labels: 0️⃣Priority: High, ⚙ Setting

#164 경기 10분 전 알림
  gsmgogo-batch/build.gradle
  gsmgogo-batch/src/main/java/team/gsmgogo/global/config/MessageConfig.java
  gsmgogo-batch/src/main/java/team/gsmgogo/global/config/SchedulerConfig.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/AlertJob.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/DailyJob.java
  gsmgogo-batch/src/main/java/team/gsmgogo/scheduler/AlertScheduler.java
  gsmgogo-batch/src/main/java/team/gsmgogo/scheduler/DailyScheduler.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/match/repository/MatchQueryDslRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/repository/UserQueryDslRepository.java
Labels: ✨Feature, 0️⃣Priority: High
