Repository GSM-GOGO/GSM-GOGO-Server, pull requests merged in 2024-03, with the labels that each got.

#10 Gradle CI
  .github/workflows/gogo_ci.yml
Labels: 0️⃣Priority: High, ⚙ Setting

#23 인증번호 발송 API 개발
  gsmgogo-api/build.gradle
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/controller/AuthController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/controller/dto/request/AuthSendCodeRequest.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/MessageSendService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/MessageSendSendServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/config/MessageConfig.java
  gsmgogo-api/src/main/resources/application.yml
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/auth/entity/VerifyCodeRedisEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/auth/repository/RefreshTokenJpaRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/auth/repository/VerifyCodeJpaRepository.java
Labels: 1️⃣Priority: Medium, ✨Feature, ♻️Refactor

#26 인증번호 인증 API
  .idea/.name
  .idea/codeStyles/codeStyleConfig.xml
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/controller/AuthController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/CheckVerifyCodeService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/MessageSendService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/CheckVerifyCodeServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/GauthLoginServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/MessageSendServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/facade/UserFacade.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/auth/entity/VerifyCodeRedisEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/entity/UserEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/enums/IsVerify.java
Labels: 1️⃣Priority: Medium, ✨Feature

#27 전화번호 등록 및 인증 API
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/controller/AuthController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/MessageSendService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/MessageSendServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/entity/UserEntity.java
Labels: 1️⃣Priority: Medium, ♻️Refactor

#58 스프링 배치 설정 및 정각에 실행되는 Job 추가
  gsmgogo-api/src/main/java/team/gsmgogo/GsmgogoApiApplication.java
  gsmgogo-api/src/main/resources/application.yml
  gsmgogo-batch/build.gradle
  gsmgogo-batch/src/main/java/team/gsmgogo/GsmgogoBatchApplication.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/ResetLoginCountJob.java
  gsmgogo-batch/src/main/java/team/gsmgogo/scheduler/ResetLoginCountScheduler.java
  gsmgogo-entity/build.gradle
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/match/entity/MatchEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/entity/UserEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/repository/UserJpaRepository.java
Labels: ✨Feature, 0️⃣Priority: High

#60 API BATCH 사이의 의존성 설정 및 health controller
  gsmgogo-api/build.gradle
  gsmgogo-api/src/main/java/team/gsmgogo/domain/health/HealthController.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/config/SecurityConfig.java
  gsmgogo-batch/build.gradle
Labels: 0️⃣Priority: High, ♻️Refactor, ⚙ Setting

#59 배드민턴 팀 등록, 응원하는 팀 등록 API 작성
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/GauthLoginServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/TeamController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/request/TeamBadmintonSaveRequest.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/request/TeamFollowRequest.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/TeamBadmintonSaveService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/TeamFollowService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamBadmintonSaveServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamDeleteServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamFollowServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamNormalSaveServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/feign/dto/GauthUserDto.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/follow/repository/FollowJpaRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/normalteamparticipate/enums/NormalTeamType.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/team/entity/TeamEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/team/enums/BadmintonRank.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/team/enums/TeamType.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/entity/UserEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/enums/Gender.java
Labels: ✨Feature, 0️⃣Priority: High

#62 복잡한 조건식을 함수로
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamBadmintonSaveServiceImpl.java
Labels: 2️⃣Priority: Low, ♻️Refactor

#63 팀 조회 API 개발 및 필요없는 스케줄러 로그 제거
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/TeamController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/response/TeamClassType.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/response/TeamListResponse.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/TeamGetService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamGetServiceImpl.java
  gsmgogo-batch/src/main/java/team/gsmgogo/job/ResetLoginCountJob.java
  gsmgogo-batch/src/main/java/team/gsmgogo/scheduler/ResetLoginCountScheduler.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/follow/repository/FollowJpaRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/team/repository/TeamJpaRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/enums/ClassEnum.java
Labels: 1️⃣Priority: Medium, ✨Feature

#64 유저 정보 검색 및 팀 등록 Validation 추가
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamNormalSaveServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamSaveServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/controller/UserController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/dto/response/UserInfoResponse.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/QueryUserInfoService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/impl/QueryUserInfoServiceImpl.java
  gsmgogo-api/src/main/resources/application.yml
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/repository/UserJpaRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/repository/dto/UserInfoQueryDto.java
Labels: ✨Feature, 0️⃣Priority: High

#66 팀 목록 리스트 DTO 수정
  gsmgogo-api/src/main/java/team/gsmgogo/global/config/SecurityConfig.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/exception/GlobalExceptionHandler.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/security/jwt/TokenProvider.java
Labels: 1️⃣Priority: Medium

#78 인증번호 전송 테스트 로직 인증 추가
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/controller/AuthController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/controller/dto/request/AuthSendCodeRequest.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/MessageSendServiceImpl.java
Labels: 1️⃣Priority: Medium, 🐛Bug

#68 일반 팀 상세정보 API
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/controller/AuthController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/SkipVerifyService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/CheckVerifyCodeServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/GauthLoginServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/MessageSendServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/SkipVerifyServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/TeamController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/response/NormalTeamParticipateDto.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/response/TeamNormalInfoDto.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/response/TeamNormalListResponse.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/TeamNormalDetailGetService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamNormalDetailGetServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/normalteamparticipate/repository/NormalTeamParticipateJpaRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/team/repository/TeamJpaRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/entity/UserEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/enums/IsVerify.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/repository/UserJpaRepository.java
Labels: 1️⃣Priority: Medium, ✨Feature

#76 팀 포메이션 조회 API
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/TeamController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/response/FormationParticipateDto.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/response/TeamFormationResponse.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/TeamFormationGetService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamBadmintonSaveServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamFormationGetServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamNormalSaveServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamSaveServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/team/entity/TeamEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/teamparticipate/repository/TeamParticipateJpaRepository.java
Labels: ✨Feature, 0️⃣Priority: High

#86 @Transactional 추가
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/MessageSendServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/SkipVerifyServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/TokenReissueServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamFormationGetServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamGetServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamNormalDetailGetServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/impl/QueryIsLeaderServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/impl/QueryUserFollowTeamServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/impl/QueryUserIdServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/impl/QueryUserPointServiceImpl.java
Labels: 0️⃣Priority: High, ♻️Refactor

#84 팀 이름 최대 글자수 6글자 제한
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/request/TeamBadmintonSaveRequest.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/request/TeamSaveRequest.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/team/entity/TeamEntity.java
Labels: 🥢Simple, 0️⃣Priority: High

#80 팀 등록, 일반 팀 등록의 인원 수, 성별 Validation
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamNormalSaveServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamSaveServiceImpl.java
Labels: ✨Feature, 0️⃣Priority: High

#83 유저 리스트 조회 API
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/controller/UserController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/QueryUserListService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/user/service/impl/QueryUserListServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/repository/UserJpaRepository.java
Labels: 1️⃣Priority: Medium, ✨Feature

#79 JWT 예외 처리
  gsmgogo-api/src/main/java/team/gsmgogo/global/config/SecurityConfig.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/exception/error/TokenException.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/facade/UserFacade.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/security/jwt/TokenProvider.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/security/jwt/filter/ErrorObject.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/security/jwt/filter/TokenExceptionFilter.java
  gsmgogo-api/src/main/java/team/gsmgogo/global/security/jwt/filter/TokenFilter.java
Labels: 1️⃣Priority: Medium, 🐛Bug

#88 Spring Batch 메타데이터 테이블 자동 생성 #87
  gsmgogo-api/src/main/resources/application.yml
Labels: 0️⃣Priority: High, ⚙ Setting

#90 Team, Follow, User 연관관계 CASCADE 설정
  gsmgogo-api/src/main/resources/application.yml
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/team/entity/TeamEntity.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/entity/UserEntity.java
Labels: 🐛Bug, 0️⃣Priority: High

#92 포메이션 상세 조회 API 팀 이름 누락
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/response/TeamFormationResponse.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamFormationGetServiceImpl.java
Labels: 🐛Bug, 0️⃣Priority: High

#94 팀 등록시 중복 팀 validation 오류
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamBadmintonSaveServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamNormalSaveServiceImpl.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamSaveServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/team/repository/TeamJpaRepository.java
Labels: 🐛Bug, 0️⃣Priority: High

#95 유저 랭킹 리스트 API 작성
  gsmgogo-api/src/main/java/team/gsmgogo/domain/rank/controller/RankController.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/rank/controller/dto/response/RankListResponse.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/rank/service/QueryUserRankService.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/rank/service/impl/QueryUserRankServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/repository/UserJpaRepository.java
Labels: ✨Feature, 0️⃣Priority: High

#98 일반 팀 리스트에서 is_my_team 속성이 모두 false만 나오는 이슈 해결
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamGetServiceImpl.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/normalteamparticipate/repository/NormalTeamParticipateJpaRepository.java
Labels: 🐛Bug, 0️⃣Priority: High

#101 일반 팀 상세 조회 Response 누락 필드 추가
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/controller/dto/response/TeamNormalListResponse.java
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamNormalDetailGetServiceImpl.java
Labels: 🐛Bug, 0️⃣Priority: High

#99 QueryDSL 벌크 쿼리 및 의존성
  .gitignore
  gsmgogo-batch/src/main/java/team/gsmgogo/job/ResetLoginCountJob.java
  gsmgogo-batch/src/main/java/team/gsmgogo/scheduler/ResetLoginCountScheduler.java
  gsmgogo-entity/build.gradle
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/repository/UserJpaRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/domain/user/repository/UserQueryDslRepository.java
  gsmgogo-entity/src/main/java/team/gsmgogo/global/config/QueryDslConfig.java
Labels: 1️⃣Priority: Medium, 🐛Bug, ♻️Refactor

#102 배드민턴 팀 등록 중복 확인 Validation 수정
  gsmgogo-api/src/main/java/team/gsmgogo/domain/team/service/impl/TeamBadmintonSaveServiceImpl.java
Labels: 1️⃣Priority: Medium, 🐛Bug

#107 Update setAllowedOrigins All
  gsmgogo-api/src/main/java/team/gsmgogo/global/config/SecurityConfig.java
Labels: 🐛Bug, 0️⃣Priority: High

#108 Update setAllowedOrigins All
  gsmgogo-api/src/main/java/team/gsmgogo/global/config/SecurityConfig.java
Labels: 🐛Bug, 0️⃣Priority: High

#116 Api, Batch 모듈 각각 빌드 및 배포
  .github/workflows/gogo_cd.yml
  Api.Dockerfile
  Batch.Dockerfile
Labels: 🐛Bug, 0️⃣Priority: High, ♻️Refactor

#122 cors origin 추가
  gsmgogo-api/src/main/java/team/gsmgogo/global/config/SecurityConfig.java
Labels: 0️⃣Priority: High, ⚙ Setting

#126 인증번호 횟수 일일 3회
  gsmgogo-api/src/main/java/team/gsmgogo/domain/auth/service/impl/MessageSendServiceImpl.java
Labels: 🐛Bug, 0️⃣Priority: High
